### ISSUE TITLE
Missing gatsby-express.json example in documentation

### ISSUE THREAD

**Issue by vvozibic** [wille/gatsby-plugin-express#1]
Hey! Please, add example `gatsby-express.json` in documentation. Because I really don't understand what I should do with this file.

**Comment by rafcontreras** [comment]
Hey @VladBlow the plugin generates this file to tell express about the routes. You don't need to do anything, you could add it to your gitignore if you want to take it out of you commits in case you're adding new page paths in the future.

**Comment by mariorodriguespt** [comment]
@VladBlow Check the build script on this issue: https://github.com/wille/gatsby-plugin-express/issues/2
