### ISSUE TITLE
Where to put express code

### ISSUE THREAD

**Issue by morfarpeter** [wille/gatsby-plugin-express#4]
Hi

I can't quite figure out where to put all the express code. Gatsby by default created HTML pages. How can I e.g. with Netlify make it use an app.js file and use as serverside node file? 

/Peter

**Comment by arhoy** [comment]
@DesignMonkey have you figured this out? I am desperately looking for better documentation or a starter template I can reference.

**Comment by ant2400** [comment]
Any updates here? I've also been searching the internet for this.

**Comment by arhoy** [comment]
@ant2400 What are you trying to do?

**Comment by stormwild** [comment]
@arhoy @ant2400 @DesignMonkey 

May help:


## Usage

Install the plugin.

```bash
npm i gatsby-plugin-express
```

or

```bash
yarn add gatsby-plugin-express
```

Create the configuration file.

```bash
mkdir config
touch config/gatsby-express.json
```

Add the plugin to `gatsby-config.js`

```js
plugins: [
  {
    resolve: 'gatsby-plugin-express',
    options: {
      output: 'config/gatsby-express.json',
    }
  }
]
```

You can create your express app anywhere in the project.

In this example, `server.js` is created in the project root with the following content:

```js
const gatsbyExpress = require('gatsby-plugin-express');
const app = express();

// serve static files before gatsbyExpress
app.use(express.static('public/'));
app.use(gatsbyExpress('config/gatsby-express.json', {
  publicDir: 'public/',
  template: 'public/404/index.html',

  // redirects all /path/ to /path
  // should be used with gatsby-plugin-remove-trailing-slashes
  redirectSlashes: true,
}));

app.listen(3000, function() {
  console.log('App started on port 3000');
});
```

Build the site

```bash
gatsby build
```

Serve the site using your express app.

```bash
node server.js
```

View the site on `http://localhost:3000`

During development, when running `gatsby develop`, gatsby provides its own express application to serve the site.

You can hook into the express used by Gatsby using the [Gatsby APIs - Advanced Proxying](https://www.gatsbyjs.org/docs/api-proxy/#advanced-proxying).

**Comment by pmourer** [comment]
I'm a bit confused by your example, `express` seems to be undefined? where do we `require('express')` ?

**Comment by stormwild** [comment]
> I'm a bit confused by your example, `express` seems to be undefined? where do we `require('express')` ?

@pmourer `const express = require('express')` can be added near the top of `server.js`

```js
const express = require('express')
const gatsbyExpress = require('gatsby-plugin-express');
const app = express();

// serve static files before gatsbyExpress
app.use(express.static('public/'));
app.use(gatsbyExpress('config/gatsby-express.json', {
  publicDir: 'public/',

  // redirects all /path/ to /path
  // should be used with gatsby-plugin-remove-trailing-slashes
  redirectSlashes: true,
}));

app.listen(3000, function() {
  console.log('App started on port 3000');
});
```

You can also checkout this working sample: [https://github.com/stormwild/gatsby-express](https://github.com/stormwild/gatsby-express).

@DesignMonkey

> How can I e.g. with Netlify make it use an app.js file and use as serverside node file?

> Dennis Support Engineer Jan 15
>
> Hi @aswanthv2, you won’t be able to run a node server on Netlify. Nor would you be able to host a database directly on Netlify. Being a JAMstack 36 service, you can host your frontend (html, css, javascript only) on Netlify. If you need to find another solution if you need to run a full server and database.

[https://community.netlify.com/t/deploying-node-js-application-in-netlify/7378](https://community.netlify.com/t/deploying-node-js-application-in-netlify/7378)

[How to run Express.js apps with Netlify Functions](https://www.netlify.com/blog/2018/09/13/how-to-run-express.js-apps-with-netlify-functions/)

**Comment by cdennington** [comment]
This example appears to work great: https://github.com/stormwild/gatsby-express

Even after upgrading to Gatsby 4.9.3

However, whenever I add a route and visit it in my browser I get the Gatsby 404 page, whether I'm running develop or after building.

The route never actually hits the node server.

I have the following route set up:
`app.get('/api/welcome', (req, res) => {
  return res.status(200).json({
    success: true,
    message: 'Welcome to my api'
  })
})`

And I've added the proxy to gatsby-config:
`developMiddleware: app => {
    app.use(
      '/api/',
      createProxyMiddleware({
        target: 'http://localhost:3000',
      })
    )
  },`

Has anyone else managed to get routes set up and running from their express server?
